version: "3.8"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  users:
    build:
      context: ./users
      dockerfile: ./Dockerfile
    container_name: users
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  posts:
    build:
      context: ./posts
      dockerfile: ./Dockerfile
    container_name: posts
    restart: always
    env_file:
      - .env
    ports:
      - "7979:7979"
    depends_on:
      - postgres
      - users
    networks:
      - app-network

  messages:
    build:
      context: ./messages
      dockerfile: ./Dockerfile
    container_name: messages
    env_file:
      - .env
    ports:
      - "9999:9999"
    restart: always
    depends_on:
      - postgres
      - users
    networks:
      - app-network

  cdn:
    build:
      context: ./cdn
    container_name: cdn
    env_file:
      - .env
    ports:
      - "8787:8787"
    restart: always
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    # volumes:
    #   - redis:/data
    networks:
      - app-network

  # client:
  #   build:
  #     context: ./client
  #   container_name: client
  #   ports:
  #     - "3000:3000"
  #   # restart: always
  #   depends_on:
  #     - users
  #     # - cdn
  #     - messages
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #     - /app/.next
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  redis:
    driver: local
