import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WebSocketProvider } from "@/hooks/socket-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " relative flex flex-col min-h-screen mx-auto max-w-[600px] border-x border-x-neutral-200"
        }
      >
        <WebSocketProvider>{children}</WebSocketProvider>
      </body>
    </html>
  );
}
